Planexa 2 handlers usecases
go-park-mail-ru/2022_1_SamoeKrNaz pull request #11
Opened 2022-04-05 16:24 UTC by shevvvo

2022-04-05 21:15 UTC, TonyBlock requested changes

2022-04-05 21:15 UTC, TonyBlock commented on repositories/board.go
> +func (boardRepository *BoardRepository) Update(board models.Board) error {
Почему решили отказаться от указателя?

2022-04-05 21:15 UTC, TonyBlock commented on repositories/board.go
> +func (boardRepository *BoardRepository) GetUserBoards(IdU uint) ([]models.Board, error) {
Почему решили отказаться от указателя?

2022-04-05 21:15 UTC, TonyBlock commented on usecases/impl/board.go
> +//++++++++++
Что означают эти плюсики?

2022-04-05 21:15 UTC, TonyBlock commented on usecases/impl/board.go
> +		return models.Board{}, customErrors.ErrUserHasntBoards
Напомни, что это за ошибка? Это какой http статус?

2022-04-05 21:15 UTC, TonyBlock commented on usecases/impl/board.go
> +		return customErrors.ErrUnauthorized
А не лучше ли возвращать ошибку, которая соответствует статусу Forbidden?

2022-04-05 21:15 UTC, TonyBlock commented on usecases/impl/board.go
> +		return customErrors.ErrUnauthorized
forbidden

2022-04-05 21:15 UTC, TonyBlock commented on usecases/impl/user.go
> +	return err
Можно в одну строку уложить

2022-04-05 21:15 UTC, TonyBlock commented on usecases/impl/user.go
> +	return token, err
Можно сделать так, что если возникла ошибка, то токен вернуть пустым

2022-04-07 08:26 UTC, TonyBlock requested changes

2022-04-07 08:26 UTC, TonyBlock commented on errors/errors.go
> +	ErrUserHasntBoards: http.StatusForbidden,
Где используется эта ошибка? И почему Forbidden?

2022-04-07 08:26 UTC, TonyBlock commented on initial_router_config.go
> +		return nil
Может хотя бы что-то вывести? А то у вас база не поднимется и вы даже не узнаете, почему

2022-04-07 08:26 UTC, TonyBlock commented on initial_router_config.go
> +
В чем смысл этой пустой строки?

2022-04-07 08:26 UTC, TonyBlock commented on initial_router_config.go
Зачем эта пустая строка?

2022-04-07 08:26 UTC, TonyBlock commented on main.go
> +	}
Лучше дополнительно возвращать ошибку, которую и выводить

2022-04-07 08:26 UTC, TonyBlock commented on repositories/board.go
> +func (boardRepository *BoardRepository) AccessToBoard(IdU uint, IdB uint) (bool, error) {
Так как у тебя возвращается bool имеет смысл назвать метод так, чтобы он начинался с Is

2022-04-07 08:26 UTC, TonyBlock commented on repositories/board.go
> +	boards := new(models.Board)
Почему во множественном числе?

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/board.go
> +	}
Лучше заменить эту проверку предваряющим получению по id вызову метода AccessBoard

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/board.go
> +	}
И тогда ошибка ErrUserHasntBoards не особо имеет смысл к существованию

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/board.go
> +	}
Давай лучше проверку на доступ к доске вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/board.go
> +	}
Давай лучше проверку на доступ к доске вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/list.go
> +	// достаю все списки тасков из БД по айди доски
Добавь проверку на доступ к доске вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/list.go
> +	// доставю список из бд
Добавь проверку на доступ к списку вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/list.go
> +	// создаю список в бд, получаю айди листа
Добавь проверку на доступ к доске вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/list.go
> +}
А где здесь используется передаваемый boardId?

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/list.go
> +	// проверяю может ли юзер редачить
Добавь проверку на доступ к списку вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/list.go
> +	// проверяю есть ли такой лист и может ли юзер удалить его
Добавь проверку на доступ к списку вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/task.go
> +	// достаю все таски из БД по айди доски
Добавь проверку на доступ к списку вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/task.go
> +	// доставю таск из бд
Добавь проверку на доступ к таске вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/task.go
> +	// создаю таск в бд, получаю айди таска
Добавь проверку на доступ к списку вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/task.go
> +	// проверяю может ли юзер редачить
Добавь проверку на доступ к таске вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/task.go
> +	// проверяю есть ли такой таск и может ли юзер удалить его
Добавь проверку на доступ к таске вызовом соответствующего метода

2022-04-07 08:26 UTC, TonyBlock commented on usecases/impl/user.go
> +}
Лучше вынеси этот метод в новый файл в utils

2022-04-07 22:18 UTC, TonyBlock requested changes

2022-04-07 22:18 UTC, TonyBlock commented on repositories/board.go
>  	return boardRepository.db.Create(board).Error
Вообще, я так подумал, вроде на вход надо подавать адрес, а значит или передаем указатель или используем &

2022-04-07 22:18 UTC, TonyBlock commented on repositories/board.go
>  	return boardRepository.db.Create(board).Error
Везде просмотри это и исправь

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/board.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/board.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/board.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/list.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/list.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/list.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/list.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/list.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/task.go
> +	}
Где обработка ошибки?

2022-04-07 22:18 UTC, TonyBlock commented on usecases/impl/task.go
> +	}
А если тасок вообще нет?

2022-04-08 09:04 UTC, TonyBlock commented on usecases/impl/task.go
> +	tasks, err := taskUseCase.repTask.GetTasks(listId)
Нет обработки ошибки

2022-04-08 09:04 UTC, TonyBlock commented on usecases/impl/task.go
> +	}
Нет обработки ошибки

2022-04-08 09:04 UTC, TonyBlock commented on usecases/impl/task.go
> +	}
Нет обработки ошибки

2022-04-08 09:04 UTC, TonyBlock commented on usecases/impl/task.go
> +	}
Нет обработки ошибки

2022-04-08 09:04 UTC, TonyBlock commented on usecases/impl/task.go
> +	}
Вопрос все еще актуален. Если мы обращаемся к 0 элементу слайса, а слайс пустой, то будет больно

2022-04-08 21:59 UTC, TonyBlock approved these changes

2022-04-09 09:01 UTC, yalublukotikov approved these changes

2022-04-09 10:01 UTC, merged