Planexa-gorm_test
go-park-mail-ru/2022_1_SamoeKrNaz pull request #14
Opened 2022-04-09 21:20 UTC by yalublukotikov

2022-04-09 21:32 UTC, TonyBlock requested changes
Радуете вы меня сегодня)

2022-04-09 21:32 UTC, TonyBlock commented on repositories/user_test.go
> +	//}
Такое выпиливаем

2022-04-09 21:32 UTC, TonyBlock commented on repositories/user_test.go
> +	gorm, err := gorm.Open(postgres.New(postgres.Config{Conn: db}))
Давай переименнуем переменную, чтобы она не пересекалась с названием пакета

2022-04-09 21:32 UTC, TonyBlock commented on repositories/list_test.go
> +	gorm, err := gorm.Open(postgres.New(postgres.Config{Conn: db}))
Давай переименнуем переменную, чтобы она не пересекалась с названием пакета

2022-04-09 21:32 UTC, TonyBlock commented on repositories/board_test.go
> +	gorm, err := gorm.Open(postgres.New(postgres.Config{Conn: db}))
Давай переименнуем переменную, чтобы она не пересекалась с названием пакета

2022-04-09 21:56 UTC, TonyBlock approved these changes

2022-04-10 08:56 UTC, shevvvo approved these changes

2022-04-10 10:00 UTC, merged