Planexa-1 server signin signup
go-park-mail-ru/2022_1_SamoeKrNaz pull request #2
Opened 2022-03-04 10:33 UTC by shevvvo

2022-03-04 14:57 UTC, TonyBlock requested changes
В целом все выглядит уже очень хорошо.
Давай еще создадим дополнительный файл, в котором будут храниться все ошибки, связанные с бизнес логикой (по типу конфликта при совпадении имен при регистрации). Будет вообще супер, если каждой ошибке будет соответствовать код статуса, с которым она возвращается.

И ещё, на всякий случай напоминаю, что на реализацию надо будет писать тесты

2022-03-04 14:57 UTC, TonyBlock commented on main.go
> +}
Давай, чтобы было красиво, сделаем отдельную структуру, которая будет выполнять всё то, что ты здесь написал. Так мы вынесем практически всю логику из main (желательно даже в отдельный файл, но пакет тот же) и избавимся от глобальной переменной

2022-03-04 14:57 UTC, TonyBlock commented on main.go
> +	config.AllowMethods = []string{"GET", "POST", "PUT", "DELETE"}
Ничего не забыл?)

2022-03-04 14:57 UTC, TonyBlock commented on main.go
> +	cors.DefaultConfig()
Зочем?

2022-03-04 14:57 UTC, TonyBlock commented on main.go
> +	router.Run()
Просто совет, лучше явно указывать порт, на котором будет крутиться сервер. Так, если вам ближе к третьему рк потребуется его поменять, хватит изменения в файлике конфига (который у вас должен будет в какой-то момент появится, но пока не думай об этом)

2022-03-04 14:57 UTC, TonyBlock commented on main.go
> +	router.Run()
Нет обработки ошибок

2022-03-04 14:57 UTC, TonyBlock commented on main.go
> +	router.POST("/api/register", handlers.Register)
Чтобы каждый раз не писать /api присмотрись к https://pkg.go.dev/github.com/gin-gonic/gin@v1.7.4#RouterGroup.Group

2022-03-04 14:57 UTC, TonyBlock commented on main.go
> +	router.POST("/api/register", handlers.Register)
Лучше вынести пути в какой-нибудь файлик с настройками, чтобы опять же всё хранилось в одном месте и это было удобно исправлять

2022-03-04 14:57 UTC, TonyBlock commented on models/models.go
> +package models
Лучше разнести структуры на разные файлы

2022-03-04 14:57 UTC, TonyBlock commented on models/models.go
> +}
Это можешь тоже вынести одним куском в отдельный файл, чтобы, когда появится база, можно было легко его убрать

2022-03-04 14:57 UTC, TonyBlock commented on models/models.go
> +	Date        string `json:"date"`
Дата чего? Создания?

2022-03-04 14:57 UTC, TonyBlock commented on models/models.go
> +	Id       int    `json:"id"`
Почему именно такой тип?

2022-03-04 14:57 UTC, TonyBlock commented on go.mod
> +module main
Название модуля лучше заменить на что-то, отражающее ваш проект (например PLANEXA_backend)

2022-03-04 14:57 UTC, TonyBlock commented on handlers/handlers.go
> +	return strconv.FormatInt(rand.Int63(), 16)
Так точно не пойдет. У тебя тут псевдорандом, который легко предсказать. Используй лучше https://pkg.go.dev/github.com/google/uuid@v1.3.0#NewString

2022-03-04 14:57 UTC, TonyBlock commented on handlers/handlers.go
> +			}
Можно добавить break в случае несовпадения паролей

2022-03-05 15:14 UTC, TonyBlock commented on models/models.go
> +package models
Можно было не разделять уже на папки) Файлов бы хватило

2022-03-05 15:15 UTC, TonyBlock commented on main.go
> +}
Ок, то, как сделал, тоже можно

2022-03-05 15:15 UTC, TonyBlock commented on main.go
> +}
done

2022-03-05 15:15 UTC, TonyBlock commented on main.go
> +	cors.DefaultConfig()
done

2022-03-05 15:15 UTC, TonyBlock commented on main.go
> +	config.AllowMethods = []string{"GET", "POST", "PUT", "DELETE"}
done

2022-03-05 15:16 UTC, TonyBlock commented on main.go
> +	router.Run()
done

2022-03-05 15:17 UTC, TonyBlock commented on main.go
> +	router.Run()
Обработка добавилась, но и одновременно нет. Ты же никуда не выводишь ошибку

2022-03-05 15:17 UTC, TonyBlock commented on main.go
> +	router.POST("/api/register", handlers.Register)
done, но появился новый прикол

2022-03-05 15:17 UTC, TonyBlock commented on main.go
> +	router.POST("/api/register", handlers.Register)
done

2022-03-05 15:21 UTC, TonyBlock commented on models/models.go
> +	CookieId  string `json:"cookie_id"`
done

2022-03-05 15:21 UTC, TonyBlock commented on models/models.go
> +}
done

2022-03-05 15:23 UTC, TonyBlock commented on models/models.go
> +	Img         string `json:"img"`
done

2022-03-05 15:23 UTC, TonyBlock commented on models/models.go
> +	Date        string `json:"date"`
done

2022-03-05 15:23 UTC, TonyBlock commented on models/models.go
> +	Id       int    `json:"id"`
done

2022-03-05 15:23 UTC, TonyBlock commented on models/models.go
> +	Id          int    `json:"id"`
done

2022-03-05 15:24 UTC, TonyBlock commented on go.mod
> +module main
done

2022-03-05 15:25 UTC, TonyBlock commented on models/models.go
> +}
У тебя уже есть юзер с id = 3

2022-03-05 15:25 UTC, TonyBlock commented on handlers/handlers.go
> +				c.SetCookie("token", token, 3600, "", "", false, true)
done

2022-03-05 15:26 UTC, TonyBlock commented on handlers/handlers.go
> +	return strconv.FormatInt(rand.Int63(), 16)
done

2022-03-05 15:26 UTC, TonyBlock commented on handlers/handlers.go
> +			}
done

2022-03-05 15:26 UTC, TonyBlock commented on handlers/handlers.go
> +	c.JSON(http.StatusOK, gin.H{"is_registered": true})
done

2022-03-05 15:43 UTC, TonyBlock requested changes

2022-03-05 15:43 UTC, TonyBlock commented on Procfile
> +web: bin/planexa
Это хто и зачем?

2022-03-05 15:43 UTC, TonyBlock commented on handlers/handlers.go
> +var cookieTime = 604800
Оставь пж коммент, в котором будет написано, сколько это в нормальном времени, а не УЕ

2022-03-05 15:43 UTC, TonyBlock commented on handlers/handlers.go
> +	//token, err := c.Cookie("token")
Закомменченный код убираем

2022-03-05 15:43 UTC, TonyBlock commented on handlers/handlers.go
> +	//token, err := c.Cookie("token")
Закомменченный код убираем

2022-03-05 15:43 UTC, TonyBlock commented on handlers/handlers_test.go
> +}
Я так понимаю, на тесты я пока не смотрю)))

2022-03-05 15:43 UTC, TonyBlock commented on initial_router_config.go
> +	"main/routes"
Не изменил название модуля

2022-03-05 15:43 UTC, TonyBlock commented on initial_router_config.go
> +	mainRoutes := router.Group("/api")
/api тоже вынеси в routes

2022-03-05 15:43 UTC, TonyBlock commented on initial_router_config.go
> +		mainRoutes.GET(routes.HomeRoute, handlers.GetBoards)
Раз тебе нужно указать путь к /api, то хватит в первом параметре написать ""

2022-03-05 15:43 UTC, TonyBlock commented on models/session_model/session.go
> +	CookieValue string `json:"cookie_va;ue"`
ue?))))

2022-03-05 15:43 UTC, TonyBlock commented on routes/routes.go
> +var RegisterRoute = "/api/register"
var (
// 1 переменная
// 2 переменная
// 3 переменная
)

2022-03-05 15:43 UTC, TonyBlock commented on routes/routes.go
> +var LoginRoute = "/api/login"
Ты же уже используешь Group, он автоматом приклеивает /api

2022-03-06 13:19 UTC, TonyBlock commented on main.go
> +	router.Run()
Давай будет выводить не твое сообщение, а собственно саму ошибку

2022-03-06 13:19 UTC, TonyBlock commented on models/models.go
> +package models
done

2022-03-06 13:20 UTC, TonyBlock commented on models/models.go
> +}
done

2022-03-06 13:20 UTC, TonyBlock commented on Procfile
> +web: bin/planexa
done

2022-03-06 13:20 UTC, TonyBlock commented on handlers/handlers.go
> +var cookieTime = 604800
done

2022-03-06 13:20 UTC, TonyBlock commented on handlers/handlers.go
> +	//token, err := c.Cookie("token")
done

2022-03-06 13:21 UTC, TonyBlock commented on handlers/handlers.go
> +	//token, err := c.Cookie("token")
done

2022-03-06 13:21 UTC, TonyBlock commented on handlers/handlers_test.go
> +}
Теперь смотрю, но пока прикрыв один глаз)

2022-03-06 13:24 UTC, TonyBlock commented on initial_router_config.go
> +	"main/routes"
done

2022-03-06 13:24 UTC, TonyBlock commented on initial_router_config.go
> +	mainRoutes := router.Group("/api")
done

2022-03-06 13:24 UTC, TonyBlock commented on initial_router_config.go
> +		mainRoutes.GET(routes.HomeRoute, handlers.GetBoards)
done

2022-03-06 13:24 UTC, TonyBlock commented on models/session_model/session.go
> +	CookieValue string `json:"cookie_va;ue"`
done

2022-03-06 13:24 UTC, TonyBlock commented on routes/routes.go
> +var RegisterRoute = "/api/register"
done

2022-03-06 13:24 UTC, TonyBlock commented on routes/routes.go
> +var LoginRoute = "/api/login"
done

2022-03-06 13:32 UTC, TonyBlock requested changes

2022-03-06 13:32 UTC, TonyBlock commented on handlers/handlers.go
> +	boardModel "PLANEXA_backend/models"
Почему boardModel?

2022-03-06 13:32 UTC, TonyBlock commented on initial_router_config.go
> +	config.AllowOrigins = []string{"https://planexa.netlify.app"}
Добавь и адрес тачки, чтобы были на всякий случай, оба адреса

2022-03-06 13:32 UTC, TonyBlock commented on models/board.go
> +	{3, "board3", "descr3", "22.02.2024"},
Чтобы потом уже не исправлять, замени заранее на что-то осмысленное. На рк просят показывать данные, которые выглядят правдоподобно для сервиса

2022-03-06 13:32 UTC, TonyBlock commented on models/user.go
> +	{3, "user3", "pass3"},
Чтобы потом уже не исправлять, замени заранее на что-то осмысленное. На рк просят показывать данные, которые выглядят правдоподобно для сервиса

2022-03-07 08:42 UTC, TonyBlock commented on main.go
> +	router.Run()
done

2022-03-07 08:42 UTC, TonyBlock commented on handlers/handlers.go
> +	boardModel "PLANEXA_backend/models"
done

2022-03-07 08:44 UTC, TonyBlock commented on initial_router_config.go
> +	config.AllowOrigins = []string{"https://planexa.netlify.app"}
Какой адрес добавил? К тебе же будет стучаться не ты сам, а фронт

2022-03-07 08:45 UTC, TonyBlock commented on models/board.go
> +	{3, "board3", "descr3", "22.02.2024"},
Давай, пожалуйста, без мемов на рк. Мне то норм, а вот преподы могут и осудить призывы любить котиков

2022-03-07 08:46 UTC, TonyBlock commented on models/user.go
> +	{3, "user3", "pass3"},
Скажем "Нет" мемам на рк. Лучше не рискуйте и укажите норм пользователей

2022-03-07 10:44 UTC, TonyBlock commented on handlers/handlers_test.go
> +}
Смотри, чтобы избавится от ошибок в тестах из-за гонок нужно:
- чтобы был мьютекс для юзеров и мьютекс для сессий
- при входе в хэндлер, который обрабатывает сессии или юзеров прописывай
`some_mutex.Lock`
`defer some_mutex.Unlock`
Для чтения соответственно RLock и RUnlock

+ не забудь добавить мьютексы в тестах только там, где они нужны

2022-03-07 10:47 UTC, TonyBlock requested changes

2022-03-07 10:47 UTC, TonyBlock commented on utils/check_password.go
> +		return errors.New("the password should be longer than 6 characters")
Давай эту ошибку тоже вынесем в файл с ошибками

2022-03-07 10:47 UTC, TonyBlock commented on utils/check_password.go
> +			return errors.New("the password should contains Latin characters and numbers")
Давай эту ошибку тоже вынесем в файл с ошибками

2022-03-07 10:47 UTC, TonyBlock commented on handlers/handlers.go
> +	}
Ничего не забыл?)

2022-03-07 20:57 UTC, TonyBlock commented on handlers/handlers_test.go
> +}
done

2022-03-07 20:57 UTC, TonyBlock commented on initial_router_config.go
> +	config.AllowOrigins = []string{"https://planexa.netlify.app"}
done

2022-03-07 20:58 UTC, TonyBlock commented on models/board.go
> +	{3, "board3", "descr3", "22.02.2024"},
Еще меньше мемом, чтобы прям вообще было не подкопаться

2022-03-07 20:58 UTC, TonyBlock commented on models/user.go
> +	{3, "user3", "pass3"},
done

2022-03-07 20:59 UTC, TonyBlock commented on utils/check_password.go
> +		return errors.New("the password should be longer than 6 characters")
Можешь сделать 2 ошибки под разные ситуации

2022-03-07 20:59 UTC, TonyBlock commented on utils/check_password.go
> +			return errors.New("the password should contains Latin characters and numbers")
отписал выше

2022-03-07 21:02 UTC, TonyBlock commented on handlers/handlers.go
> +	}
done

2022-03-07 21:19 UTC, TonyBlock requested changes
Добавь logout (по api опять же обсудите) и тесты на неё.
Для правильного подсчета покрытия + гонок можешь использовать эту команду
`go test -race -coverpkg=./... -coverprofile=c.out ./...; go tool cover -func=c.out`

2022-03-07 21:19 UTC, TonyBlock commented on handlers/handlers.go
> +var lockSess = sync.RWMutex{}
var (
//
//
//
)

2022-03-07 21:19 UTC, TonyBlock commented on handlers/handlers.go
> +		c.JSON(customErrors.ConvertErrorToCode(customErrors.ErrPassword), gin.H{"error": err.Error()})
зачем здесь обращаться к конкретной ошибке? Подставляй полученную err

2022-03-07 21:19 UTC, TonyBlock commented on handlers/handlers_test.go
> +	}
Лишнее

2022-03-07 21:19 UTC, TonyBlock commented on initial_router_config.go
> +}
Выпиливаем

2022-03-07 21:19 UTC, TonyBlock commented on initial_router_config.go
> +	router.Use(CORSMiddleware())
Выпиливаем

2022-03-07 21:19 UTC, TonyBlock commented on initial_router_config.go
> +	config.AllowAllOrigins = true
Выпиливаем

2022-03-07 21:19 UTC, TonyBlock commented on initial_router_config.go
> +	//config.AllowOrigins = []string{"https://planexa.netlify.app", "https://89.208.199.114:3000"}
Расскоментируй и добавь на всякий случай адрес деплоя бэка

2022-03-07 21:19 UTC, TonyBlock commented on initial_router_config.go
> +	router.Use(cors.New(config))
Поменяй местами со строчками 13-18. У вас из-за этого сам запрос обрабатывается раньше, чем корс

2022-03-07 21:19 UTC, TonyBlock commented on models/user.go
> +	Password string `json:"Password"`
Обкашляли с парнями, сделай в json с маленькой буквы

2022-03-08 11:39 UTC, TonyBlock commented on models/board.go
> +	{3, "board3", "descr3", "22.02.2024"},
done

2022-03-08 11:39 UTC, TonyBlock commented on utils/check_password.go
> +		return errors.New("the password should be longer than 6 characters")
done

2022-03-08 11:40 UTC, TonyBlock commented on utils/check_password.go
> +			return errors.New("the password should contains Latin characters and numbers")
done

2022-03-08 11:40 UTC, TonyBlock commented on handlers/handlers.go
> +var lockSess = sync.RWMutex{}
done

2022-03-08 11:40 UTC, TonyBlock commented on handlers/handlers.go
> +		c.JSON(customErrors.ConvertErrorToCode(customErrors.ErrPassword), gin.H{"error": err.Error()})
done

2022-03-08 11:41 UTC, TonyBlock commented on handlers/handlers_test.go
> +	}
done

2022-03-08 11:42 UTC, TonyBlock commented on initial_router_config.go
> +}
done

2022-03-08 11:42 UTC, TonyBlock commented on initial_router_config.go
> +	router.Use(CORSMiddleware())
done

2022-03-08 11:42 UTC, TonyBlock commented on initial_router_config.go
> +	//config.AllowOrigins = []string{"https://planexa.netlify.app", "https://89.208.199.114:3000"}
done

2022-03-08 11:42 UTC, TonyBlock commented on initial_router_config.go
> +	router.Use(cors.New(config))
done

2022-03-08 11:43 UTC, TonyBlock commented on models/user.go
> +	Password string `json:"Password"`
done

2022-03-08 11:54 UTC, TonyBlock requested changes
ДАВАЙ, ФИНАЛЬНЫЙ РЫВОК ДО ~~МИРОВОГО ГОСПОДСТВА~~ АППРУВА

2022-03-08 11:54 UTC, TonyBlock commented on errors/errors.go
> +	ErrShotPassword  = errors.New("password should be longer than 6 characters")
short (не забудь в местах вызова поменять)

2022-03-08 11:54 UTC, TonyBlock commented on handlers/c.out
> +mode: atomic
Это что за покемон, нам тут таких не надо? И ещё, судя по всему, ты запускал предложенную мною команду из папки с хэндлерами. Покрытие тестами измеряется для всего проекта => запускать надо из корня проекта

2022-03-08 11:54 UTC, TonyBlock commented on handlers/handlers.go
> +	cookieTime = 604800
Перемести комментарий про количество дней справа от переменной с временем жизни куки

2022-03-08 11:54 UTC, TonyBlock commented on utils/check_password.go
> +		return customErrors.ErrShotPassword
Вот здесь поменяй

2022-03-08 12:29 UTC, TonyBlock commented on utils/check_password.go
> +		return customErrors.ErrShotPassword
done

2022-03-08 12:29 UTC, TonyBlock commented on handlers/c.out
> +mode: atomic
done

2022-03-08 12:30 UTC, TonyBlock commented on errors/errors.go
> +	ErrShotPassword  = errors.New("password should be longer than 6 characters")
done

2022-03-08 12:30 UTC, TonyBlock approved these changes

2022-03-08 12:34 UTC, Victorius19 approved these changes

2022-03-08 12:34 UTC, yalublukotikov approved these changes

2022-03-08 12:38 UTC, TonyBlock commented on initial_router_config.go
> +	config.AllowAllOrigins = true
done

2022-03-08 12:39 UTC, merged