3.12: Репозитории листов и чеклистов
go-park-mail-ru/2022_1_SamoeKrNaz pull request #24
Opened 2022-04-23 14:36 UTC by yalublukotikov

2022-04-24 20:58 UTC, TonyBlock requested changes

2022-04-24 20:58 UTC, TonyBlock commented on repositories/checkList_repo.go
> +	GetCheckListItems(IdCl uint) (*[]models.CheckListItem, error)
У тебя же уже есть практически такой же метод в репе чеклистов

2022-04-24 20:58 UTC, TonyBlock commented on usecases/checkListItem_usecase.go
> +	GetCheckLists(userId uint, IdCl uint) (*[]models.CheckListItem, error)
Может быть GetCheckListItems?

2022-04-24 20:58 UTC, TonyBlock commented on repositories/checkList_repo.go
> +	GetCheckLists(IdT uint) ([]models.CheckList, error)
А этот метод уже есть в репе тасок

2022-04-25 21:30 UTC, TonyBlock requested changes

2022-04-25 21:30 UTC, TonyBlock commented on usecases/impl/comment.go
> +	isAccess, err := commentUseCase.repTask.IsAccessToTask(userId, currentData.IdT)
Эта проверка не совсем корректная, ведь тогда выходит так, что все те, кто имеют доступ к таске могут редачить комменты

2022-04-25 21:30 UTC, TonyBlock commented on usecases/impl/comment.go
> +	isAccess, err := commentUseCase.repTask.IsAccessToTask(userId, checkList.IdT)
Аналогично с доступом

2022-04-26 08:26 UTC, TonyBlock approved these changes

2022-04-26 09:57 UTC, Victorius19 approved these changes

2022-04-26 09:58 UTC, merged