3.01: Замутить CI на бэке
go-park-mail-ru/2022_1_SamoeKrNaz pull request #25
Opened 2022-04-23 14:56 UTC by yalublukotikov

2022-04-24 20:43 UTC, TonyBlock requested changes

2022-04-24 20:43 UTC, TonyBlock commented on .github/workflows/main.yml
> +      run: go test -race -vet=off ./...
Можно еще добавить доп проверку на подсчет покрытия тестами

2022-04-24 20:43 UTC, TonyBlock commented on .github/workflows/main.yml
> +    branches: [ '**' ]
А зачем на каждый пуш CI?

2022-04-24 20:43 UTC, TonyBlock commented on .github/workflows/main.yml
> +      run: golint ./...
Что-то неладное с вашим CI. У вас линтер много на что ругается, хотя при этом джоба проходит
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/37208985/164995763-6d46479a-c38d-44f0-b1b8-0bf2cdb49d67.png">

2022-04-25 18:09 UTC, TonyBlock approved these changes

2022-04-25 18:11 UTC, Victorius19 approved these changes

2022-04-25 18:12 UTC, merged