did service
go-park-mail-ru/2022_1_SamoeKrNaz pull request #30
Opened 2022-04-28 21:52 UTC by shevvvo

2022-04-28 22:39 UTC, TonyBlock requested changes
Добавьте привязку к докеру + пофиксите конфликты

2022-04-28 22:39 UTC, TonyBlock commented on auth_microservice/server/handler/session.proto
> +}
new line

2022-04-28 22:39 UTC, TonyBlock commented on repositories/impl/redis.go
>  type RedisRepositoryImpl struct {
Давай переименуем во что-то вроде SessionRepository (мы же именно для этого и вынесли редис в микросервис)

2022-04-28 22:39 UTC, TonyBlock commented on cmd/api/initial_router_config.go
> +		"0.0.0.0:8080",
Для того, чтобы потом с докером заработало, указывайте адрес "<название_докер_сервиса>:<порт_сервиса>"

2022-04-29 07:17 UTC, TonyBlock requested changes
Уберите бинарник сервера и добавьте его в гит игнор

2022-04-29 07:17 UTC, TonyBlock commented on docker-compose.yml
> +  session:
У тебя сейчас основной бэк зависит от редиса, а надо, чтобы от сессионного микросервиса

2022-04-29 07:39 UTC, TonyBlock requested changes

2022-04-30 09:48 UTC, TonyBlock approved these changes

2022-04-30 09:52 UTC, yalublukotikov approved these changes

2022-04-30 10:30 UTC, merged