PLANEXA-3: добавить микросервис для юзеров
go-park-mail-ru/2022_1_SamoeKrNaz pull request #33
Opened 2022-05-02 11:39 UTC by shevvvo

2022-05-02 15:36 UTC, TonyBlock requested changes

2022-05-02 15:36 UTC, TonyBlock commented on cmd/api/initial_router_config.go
> +		"2022_1_samoekrnaz_session_1:8082",
session?

2022-05-02 15:36 UTC, TonyBlock commented on repositories/impl/user.go
> +	client handler.UserServiceClient
А мы где-то обращаемся к этому клиенту?

2022-05-02 15:36 UTC, TonyBlock commented on user_microservice/server_user/server.go
> +	listener, err := net.Listen("tcp", "2022_1_samoekrnaz_session_1:8081")
Порт разве верный?

2022-05-02 15:36 UTC, TonyBlock commented on user_microservice/server_user/server.go
> +	sessUseCase := usecase_impl.CreateSessionUseCase(redis)
Session?

2022-05-02 15:36 UTC, TonyBlock commented on user_microservice/server_user/server.go
> +	listener, err := net.Listen("tcp", "2022_1_samoekrnaz_session_1:8081")
И почему session?

2022-05-02 15:36 UTC, TonyBlock commented on user_microservice/server_user/server.go
> +	handler.RegisterAuthCheckerServer(grpcSrv, impl.CreateSessionServer(sessUseCase))
Session???)

2022-05-02 19:29 UTC, TonyBlock requested changes
Поправишь, чтобы CI проходил и мы в расчете)

2022-05-02 19:32 UTC, TonyBlock requested changes
Упс, нашел еще вот это, сори

2022-05-02 19:32 UTC, TonyBlock commented on cmd/api/initial_router_config.go
> +		"2022_1_samoekrnaz_session_1:8082",
А в докер не нужно добавить этот микросервис?

2022-05-02 19:47 UTC, yalublukotikov commented on cmd/api/initial_router_config.go
> +		"2022_1_samoekrnaz_session_1:8082",
конечно нужно, еще и метрики забацать бы....

2022-05-02 21:00 UTC, TonyBlock requested changes
Зачем вам grafana_data? В гитигнор

2022-05-03 17:57 UTC, TonyBlock approved these changes

2022-05-03 20:09 UTC, TonyBlock approved these changes

2022-05-03 20:26 UTC, yalublukotikov approved these changes

2022-05-03 20:29 UTC, merged