4.03: Конфиг файл для конфигурации
go-park-mail-ru/2022_1_SamoeKrNaz pull request #39
Opened 2022-05-09 09:30 UTC by yalublukotikov

2022-05-09 20:44 UTC, TonyBlock requested changes

2022-05-09 20:44 UTC, TonyBlock commented on cmd/api/config.yml
> +postgresDbName: 'DB_Planexa'
Эти вещи лучше вообще вынести в секреты гита

2022-05-09 20:44 UTC, TonyBlock commented on user_microservice/server_user_ms/config.yml
> +postgresDbName: 'DB_Planexa'
Это тоже лучше вынести в секреты

2022-05-11 17:12 UTC, Victorius19 approved these changes

2022-05-11 18:13 UTC, merged