4.01: Вложения на бэке
go-park-mail-ru/2022_1_SamoeKrNaz pull request #40
Opened 2022-05-10 08:07 UTC by yalublukotikov

2022-05-10 12:41 UTC, TonyBlock requested changes

2022-05-10 12:41 UTC, TonyBlock commented on main_microservice/repositories/impl/attachment.go
> +	err := attachmentRepository.db.Model(&models.Attachment{}).Count(&countFiles).Error
?

2022-05-10 12:41 UTC, TonyBlock commented on main_microservice/repositories/impl/attachment.go
> +	fileName := strings.Join([]string{filePathAttach, strconv.Itoa(int(countFiles))}, "")
Плохо, тогда уж просто по id. А то выходит так, что мы создали один файл, потом еще один, удалили первый и добавили еще один. Так мы получаем два файла с одинаковым названием. Можете использовать uuid.NewString()

2022-05-11 17:12 UTC, Victorius19 approved these changes

2022-05-11 18:21 UTC, merged