Planexa 4 easyjson
go-park-mail-ru/2022_1_SamoeKrNaz pull request #48
Opened 2022-05-22 13:18 UTC by shevvvo

2022-05-22 17:11 UTC, TonyBlock requested changes
Не стал уж писать для каждого хэндлера про то, что если генерируется ошибка err, то её и стоит пробрасывать

И ещё, убери из подсчета покрытия тестами сгенерированные easyjson файлики

2022-05-22 17:11 UTC, TonyBlock commented on cmd/api/initial_router_config.go
> +	router.Use(middleware.CheckError)
Давай добавлять мидлварь сразу после добавления корса (выше по файлу)

2022-05-22 17:11 UTC, TonyBlock commented on main_microservice/handlers/attachment_handler.go
> +		_ = c.Error(customErrors.ErrBadInputData)
err пробрасываем

2022-05-22 17:11 UTC, TonyBlock commented on main_microservice/handlers/attachment_handler.go
> +		_ = c.Error(customErrors.ErrBadInputData)
err пробрасываем

2022-05-22 17:11 UTC, TonyBlock commented on main_microservice/handlers/attachment_handler.go
> +		_ = c.Error(customErrors.ErrBadInputData)
err пробрасываем

2022-05-22 17:11 UTC, TonyBlock commented on main_microservice/handlers/board_handler.go
> +		_ = c.Error(customErrors.ErrBadInputData)
err пробрасываем

2022-05-22 17:11 UTC, TonyBlock commented on main_microservice/middleware/error_middleware.go
> +	if c.Errors != nil {
Так как ты хочешь, чтобы эта мидлварь срабатывала после хэндлеров, то добавь первой строчкой c.Next()

2022-05-22 17:11 UTC, TonyBlock commented on main_microservice/middleware/error_middleware.go
> +func CheckError(c *gin.Context) {
Мидлвари немного подругому выглядят в джине https://github.com/gin-gonic/gin#custom-middleware

2022-05-22 18:11 UTC, TonyBlock approved these changes

2022-05-23 09:52 UTC, yalublukotikov approved these changes

2022-05-23 09:53 UTC, merged