2.16: Настроить docker + поднять бд
go-park-mail-ru/2022_1_SamoeKrNaz pull request #7
Opened 2022-03-26 13:59 UTC by yalublukotikov

2022-03-26 20:16 UTC, TonyBlock requested changes

2022-03-26 20:16 UTC, TonyBlock commented on docker-compose.yml
> +    build: ./
Сейчас не так актуально, но позже, когда к третьему рк вам потребуется иметь у себя несколько микросервисов, вы столкнетесь с тем, что для каждого из микросервисов нужен докерфайл. Текущее описание билда не позволяет контролировать, какой докер файл используется. Поэтому советую посмотреть на то, какие поднастройки есть у build

2022-03-26 20:16 UTC, TonyBlock commented on docker-compose.yml
> +      - ./db_postgres:/var/lib/postgresql/data
new line

2022-03-26 20:16 UTC, TonyBlock commented on docker-compose.yml
> +      - ./:/server
В целом претензий и вопрос нет, однаааако...)
Предлагаю сделать так, чтобы контейнер с кошкой ждал, пока запуститься постгрес (через depends_on)

2022-03-27 11:06 UTC, TonyBlock commented on docker-compose.yml
> +      - ./:/server
done

2022-03-27 11:06 UTC, TonyBlock commented on docker-compose.yml
> +      - ./db_postgres:/var/lib/postgresql/data
done

2022-03-27 11:06 UTC, TonyBlock commented on docker-compose.yml
> +    build: ./
done

2022-03-27 11:07 UTC, TonyBlock approved these changes

2022-03-27 11:26 UTC, Victorius19 approved these changes

2022-03-27 11:27 UTC, shevvvo approved these changes

2022-03-27 11:33 UTC, merged