2.17: БД (подключение к бд через gorn)
go-park-mail-ru/2022_1_SamoeKrNaz pull request #8
Opened 2022-03-27 11:53 UTC by yalublukotikov

2022-03-27 12:14 UTC, TonyBlock requested changes

2022-03-27 12:14 UTC, TonyBlock commented on models/board.go
> +	ImgDesk     string    `json:"img_desk"`
За что отвечает это поле?

2022-03-27 12:14 UTC, TonyBlock commented on models/board.go
> +	Title       string    `json:"title" gorm:"not null"`
Можно еще сделать индексом

2022-03-27 12:14 UTC, TonyBlock commented on models/board.go
> +	IdB         uint      `json:"idb" gorm:"primaryKey"`
В чем был смысл переименовывать поле?

2022-03-27 12:14 UTC, TonyBlock commented on models/board.go
> +	{5, "Проект", "", "Все таски проекта собраны тут, для того, чтобы мы могли эффективно вести разработку вместе. Это точно удобно!", time.Now(), 5, nil, nil},
Так и должно быть, что описание доски - пустое?

2022-03-27 12:14 UTC, TonyBlock commented on models/user.go
> +	IdP       uint    `json:"idp" gorm:"primaryKey"`
В чем был смысл переименовывать поле?

2022-03-27 12:14 UTC, TonyBlock commented on models/user.go
> +	Username  string  `json:"username" gorm:"not null;"`
Не хочешь сделать поле уникальным?

2022-03-27 12:14 UTC, TonyBlock commented on models/user.go
> +	Password  string  `json:"password" gorm:"not null;"`
Задел на будущее, неужели вы будете хранить чистый пароль?

2022-03-27 12:14 UTC, TonyBlock commented on models/list.go
> +	IdL       uint   `json:"idl" gorm:"primaryKey"`
В чем был смысл переименовывать поле?

2022-03-27 12:14 UTC, TonyBlock commented on models/list.go
> +	IdB       uint   `json:"idb"`
Я бы добавил уточнение, что поле не пустое и сделал его индексом

2022-03-27 12:14 UTC, TonyBlock commented on models/list.go
> +	ImgAvatar string `json:"img_avatar"`
Понятие аватар больше подходит юзеру

2022-03-27 12:14 UTC, TonyBlock commented on models/tasks.go
> +	IdT         uint      `json:"idt"`
В чем был смысл переименовывать поле?

2022-03-27 12:14 UTC, TonyBlock commented on models/list.go
> +}
А списку position не нужен?

2022-03-27 12:14 UTC, TonyBlock commented on models/tasks.go
> +	Position    uint      `json:"position" gorm:"unique"`
Воу вот, зачем unique?

2022-03-27 12:14 UTC, TonyBlock commented on models/tasks.go
> +	IdL         uint
not null, index

2022-03-27 12:14 UTC, TonyBlock commented on models/tasks.go
> +	IdB         uint
not null, index

2022-03-27 12:14 UTC, TonyBlock commented on models/tasks.go
> +	DateCreated time.Time `json:"dateCreated"`
Вы все-таки решили дату хранить именно в виде даты, а не строки?

2022-03-27 12:52 UTC, yalublukotikov commented on models/board.go
> +	DateCreated time.Time `json:"date"`
могу вернуться к строке

2022-03-27 12:53 UTC, yalublukotikov commented on models/board.go
> +	Title       string    `json:"title" gorm:"not null"`
а что индекс дает?

2022-03-27 12:53 UTC, yalublukotikov commented on models/board.go
> +	ImgDesk     string    `json:"img_desk"`
Виктор хотел сделать возможность добавления картинки к доске

2022-03-27 12:54 UTC, yalublukotikov commented on models/list.go
> +	IdL       uint   `json:"idl" gorm:"primaryKey"`
думал, что будет понятнее, что за индекс используется

2022-03-27 12:54 UTC, yalublukotikov commented on models/list.go
> +}
нужен

2022-03-27 12:55 UTC, yalublukotikov commented on models/tasks.go
> +	Position    uint      `json:"position" gorm:"unique"`
чтобы позиции были уникальными на всякий случай...

2022-03-27 12:55 UTC, yalublukotikov commented on models/user.go
> +	Password  string  `json:"password" gorm:"not null;"`
явно будем хешировать

2022-03-28 13:54 UTC, TonyBlock commented on models/user.go
> +	Password  string  `json:"password" gorm:"not null;"`
Просто проблема возникнет в следующем: эта структура используется вами и для считывания в нее тела запросов, связанных с профилем, так и для работы с гормом. Из-за этого в ситуации, когда вам понадобится возвращать информацию о пользователе (например, чтобы заполнить поле с логином), то по умолчанию пароль будет возвращаться (хоть и хешированный).
Я это всё к чему, просто подумайте над тем, как вам будет удобнее:
- иметь несколько полей с паролем в структуре (одно - хешированное для горма, а другое - для считывания из json)
- иметь одно поле, но следить за тем, чтобы при возврате информации о пользователе оно было не заполнено

2022-03-28 13:55 UTC, TonyBlock commented on models/tasks.go
> +	Position    uint      `json:"position" gorm:"unique"`
Но он же тогда будет уникальным среди всееех тасок на всех досках

2022-03-28 13:57 UTC, TonyBlock commented on models/board.go
> +	DateCreated time.Time `json:"date"`
Как вам удобнее)

2022-03-28 14:00 UTC, TonyBlock requested changes

2022-03-28 14:00 UTC, TonyBlock commented on models/board.go
> +	IdP         uint      `json:"idp"`
Если это id пользователя, то может стоит добавить какую-то пометку про внешний ключ?

2022-03-29 17:26 UTC, TonyBlock commented on errors/errors.go
> +	ErrIdNotExist       = errors.New("this id doesn`t exists")
Лучше переназвать эту ошибку на что-то вроде ErrUserNotFound

2022-03-29 17:27 UTC, TonyBlock commented on errors/errors.go
> +	ErrIdNotExist       = errors.New("this id doesn`t exists")
Где привязка новых ошибок к кодам статусов ниже?

2022-03-29 17:29 UTC, TonyBlock commented on handlers/handlers.go
> +				models.SessionList = append(models.SessionList, models.Session{UserId: userDB.IdP, CookieValue: token})
Не ошибка, просто напомни, пожалуйста, почему поле с id юзера называется IdP?

2022-03-29 17:33 UTC, TonyBlock commented on repositories/user.go
> +	hashPassword, err := hash.HashPassword(user.Password)
Лучше будет не только хэшировать, но и солить

2022-03-29 17:37 UTC, TonyBlock commented on repositories/user.go
> +func (userRepository *UserRepository) IsExist(username string) error {
Обычно принято, что функции с подобным названием возвращают bool значение. Если хочешь дополнительно иметь возможность проверять, что не сломалось обращение к базе, то дополнительно с bool можешь возвращать ошибку

2022-03-29 17:40 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("username = ?", username)
О, раз обращаешься к столбцу username, то можешь сделать сделать это поле в структуре индексом

2022-03-29 17:41 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("username = ?", username)
Как у тебя горм поймет, из какой таблицы брать этот столбец?

2022-03-29 17:45 UTC, TonyBlock commented on repositories/user.go
> +	return nil
Лучше return userRepository.db.Save(user)

2022-03-29 17:46 UTC, TonyBlock commented on repositories/user.go
> +	// поэтому поиск по никнейму ничего не даст, будем искать по Id
Вы как договорились? Что при запросе на обновление приходит вся информация о пользователе или только измененная?

2022-03-29 17:50 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("username = ?", username).Find(&user)
Select можно убрать

2022-03-29 17:50 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("username = ?", username).Find(&user)
Зачем передавать в find ссылку на user? Он же у тебя уже указатель

2022-03-29 17:51 UTC, TonyBlock commented on repositories/user.go
> +func (userRepository *UserRepository) GetUserByLogin(username string) *models.User {
Раз имеем дело с базой, которая может сама по каким-то моментам сломаться, то надо возвращать два значения: с полезной нагрузкой и с ошибкой

2022-03-29 17:52 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("IdP = ?", IdP).Find(&user)
Зачем передавать в find ссылку на user? Он же у тебя уже указатель

2022-03-29 17:53 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("IdP = ?", IdP).Find(&user)
При запросах по первичному ключу можно просто вызывать метод Find(user, IdP)

2022-03-29 17:55 UTC, TonyBlock commented on repositories/user.go
> +	}
Сломанная проверка. Мы ведь проверяем на то, что такой никнейм есть, а не то, что он занят

2022-03-29 17:55 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("username = ?", username, "password = ?", hashPassword).Find(&user)
Select можно убрать

2022-03-29 17:55 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Select("*").Where("username = ?", username, "password = ?", hashPassword).Find(&user)
Зачем передавать в find ссылку на user? Он же у тебя уже указатель

2022-03-29 19:20 UTC, yalublukotikov commented on handlers/handlers.go
> +				models.SessionList = append(models.SessionList, models.Session{UserId: userDB.IdP, CookieValue: token})
тут моя ошибка, забыл, что не Profile, а User

2022-03-30 07:36 UTC, yalublukotikov commented on repositories/user.go
> +	hashPassword, err := hash.HashPassword(user.Password)
по идее, солится уже внутри функции GenerateFromPassword

2022-03-30 07:45 UTC, yalublukotikov commented on repositories/user.go
> +	}
это же метод логин, как раз тут нужна проверка на занятость никнейма

2022-03-30 07:45 UTC, yalublukotikov commented on repositories/user.go
> +	}
подумал, что будет логично, если сначала проверим, есть ли такой пользователь вообще, а потом начнем считать хэш от пароля

2022-03-31 11:29 UTC, TonyBlock requested changes

2022-03-31 11:29 UTC, TonyBlock commented on repositories/list.go
> +}
В теории работает, на практике не очень, так как надо еще думать об изменении позиции других списков

2022-03-31 11:29 UTC, TonyBlock commented on repositories/task.go
> +	}
поскольку от result используется только поле error, то можно сразу к нему обращаться, добавив в конце запроса .Error

2022-03-31 11:29 UTC, TonyBlock commented on repositories/task.go
> +	}
Со сменой позиции не все так просто. Тут же важно еще помнить, что когда мы переносим одну таску, позиция других тасок в списке тоже может меняться

2022-03-31 11:29 UTC, TonyBlock commented on repositories/task.go
> +		return nil, customErrors.ErrBoardNotFound
Почему board? Мы же таску не нашли

2022-03-31 11:29 UTC, TonyBlock commented on repositories/task.go
> +	// если выборка в 0 строк, то такой доски нет
Доски?

2022-03-31 11:29 UTC, TonyBlock commented on repositories/task.go
> +		// иначе вернем доску
Доску?

2022-03-31 11:29 UTC, TonyBlock commented on repositories/task.go
> +}
В теории работает, на практике не очень, так как надо еще думать об изменении позиции других тасок в списке

2022-03-31 11:36 UTC, TonyBlock requested changes

2022-03-31 11:36 UTC, TonyBlock commented on repositories/user.go
> +	if isExist == true {
можно просто if isExist {}

2022-03-31 11:36 UTC, TonyBlock commented on repositories/user.go
> +	if err != nil {
можно сделать else if

2022-03-31 15:22 UTC, yalublukotikov commented on .gitignore
> +database.go
это мой файлик, в котором я тестирую работоспособность репозиториев

2022-03-31 20:58 UTC, TonyBlock commented on repositories/user.go
> +		if isExist == true {
Просто IsExist

2022-03-31 20:58 UTC, TonyBlock commented on repositories/user.go
> +			return err
return customErrors.ErrUsernameExist
У тебя же err == nil

2022-03-31 20:58 UTC, TonyBlock commented on repositories/user.go
> +	}
А как result может быть равен nil?

2022-03-31 20:58 UTC, TonyBlock commented on repositories/list.go
> +	}
Давай переименуем return в err, так будет логичнее

2022-03-31 21:01 UTC, TonyBlock commented on repositories/task.go
> +	}
Давай переименуем return в err, так будет логичнее

2022-03-31 21:15 UTC, TonyBlock requested changes
Перемещение списков и тасок требует значительной доработки

2022-03-31 21:15 UTC, TonyBlock commented on repositories/list.go
> +	}
Что-то есть стойкое ощущение, что тут могут быть баги. Как минимум здесь не учтено, что списки могли ранее перемещаться

2022-03-31 21:15 UTC, TonyBlock commented on repositories/list.go
> +	}
Продумай получше эту систему

2022-03-31 21:15 UTC, TonyBlock commented on repositories/list.go
> +			// позиций, на которые мы переместили и сохранить
Не совсем так) Обрати внимание, что все списки, отличные от того, который мы непосредственно перемещаем, или вообще не меняют положения или перемещаются только на +-1

2022-03-31 21:15 UTC, TonyBlock commented on repositories/list.go
> +		}
Я бы посоветовал вынести это в отдельный метод и довести до ума

2022-03-31 21:15 UTC, TonyBlock commented on repositories/user.go
> +	result := userRepository.db.Table("users").Where("username = ?", username).Find(user)
Table лишняя

2022-04-02 13:19 UTC, TonyBlock requested changes
Лайк! Осталось только добавить еще обработчики ошибок для запросов, связанных с перемещением списков/тасок

2022-04-02 13:19 UTC, TonyBlock commented on repositories/list.go
> +				Where("position > ? AND position <= ? AND id_b = ?", list.Position-1, currentData.Position-1, currentData.IdB).
Для выборки промежутка используй BETWEEN

2022-04-02 13:19 UTC, TonyBlock commented on repositories/list.go
> +				Where("position > ? AND position <= ? AND id_b = ?", list.Position-1, currentData.Position-1, currentData.IdB).
При этом не забудь, что BETWEEN работает как [n, m]

2022-04-02 13:19 UTC, TonyBlock commented on repositories/list.go
> +				Where("position > ? AND position <= ? AND id_b = ?", currentData.Position, list.Position, currentData.IdB).
Отписал по BETWEEN выше

2022-04-02 13:19 UTC, TonyBlock commented on repositories/list.go
> +	}
Давай применим наработки по сдвигу позиций и здесь

2022-04-02 13:19 UTC, TonyBlock commented on repositories/task.go
> +				Where("position > ? AND position <= ? AND id_l = ?", task.Position-1, currentData.Position-1, currentData.IdL).
BETWEEN

2022-04-02 13:19 UTC, TonyBlock commented on repositories/task.go
> +				Where("position > ? AND position <= ? AND id_l = ?", currentData.Position, task.Position, currentData.IdL).
BETWEEN

2022-04-02 13:19 UTC, TonyBlock commented on repositories/task.go
> +				Where("position > ? AND position <= ? AND id_l = ?", task.Position-1, currentData.Position-1, task.IdL).
BETWEEN

2022-04-02 13:19 UTC, TonyBlock commented on repositories/task.go
> +				Where("position > ? AND position <= ? AND id_l = ?", currentData.Position, task.Position, task.IdL).
BETWEEN

2022-04-02 13:19 UTC, TonyBlock commented on repositories/task.go
> +	}
Давай юзать алгоритм по перемещению из Update

2022-04-02 15:43 UTC, TonyBlock requested changes

2022-04-02 15:43 UTC, TonyBlock commented on repositories/list.go
> +				UpdateColumn("position", gorm.Expr("position + 1"))
Возможная ошибка не обрабатывается

2022-04-02 15:43 UTC, TonyBlock commented on repositories/list.go
> +				UpdateColumn("position", gorm.Expr("position - 1"))
Возможная ошибка не обрабатывается

2022-04-02 15:43 UTC, TonyBlock commented on repositories/list.go
> +				UpdateColumn("position", gorm.Expr("position - 1"))
От currentData.Position + 1 до list.Position. У тебя же в этой ветке старая позиция < новой

2022-04-02 15:43 UTC, TonyBlock commented on repositories/task.go
> +				UpdateColumn("position", gorm.Expr("position + 1"))
Возможная ошибка не обрабатывается

2022-04-02 15:43 UTC, TonyBlock commented on repositories/task.go
> +				UpdateColumn("position", gorm.Expr("position - 1"))
Возможная ошибка не обрабатывается

2022-04-02 15:43 UTC, TonyBlock commented on repositories/task.go
> +				UpdateColumn("position", gorm.Expr("position - 1"))
От currentData.Position + 1 до task.Position. У тебя же в этой ветке старая позиция < новой

2022-04-02 15:43 UTC, TonyBlock commented on repositories/task.go
> +			UpdateColumn("position", gorm.Expr("position - 1"))
Возможная ошибка не обрабатывается

2022-04-02 15:43 UTC, TonyBlock commented on repositories/task.go
> +				UpdateColumn("position", gorm.Expr("position + 1"))
Возможная ошибка не обрабатывается

2022-04-02 15:43 UTC, TonyBlock commented on repositories/task.go
> +				UpdateColumn("position", gorm.Expr("position - 1"))
Возможная ошибка не обрабатывается

2022-04-02 15:43 UTC, TonyBlock commented on repositories/task.go
> +				UpdateColumn("position", gorm.Expr("position - 1"))
От currentData.Position + 1 до task.Position. У тебя же в этой ветке старая позиция < новой

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +}
Эта структура уже есть в models/session.go

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +	*redis.Client
Я бы сделал это полноценным полем структуры

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +	err := redisConnect.Set(strconv.Itoa(int(user.idU)), user.cookie, 259200*time.Second).Err()
Что из это ключ, а что - значение?

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +	err := redisConnect.Set(strconv.Itoa(int(user.idU)), user.cookie, 259200*time.Second).Err()
У вас уже есть время жизни сессии в хэндлере

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +	return err
return <выражение>

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +		return "", customErrors.ErrUnauthorized
Оставь подстановку конкретной ошибки другим слоям

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +	value, err := redisConnect.Get(strconv.Itoa(int(user.idU))).Result()
Лучше не Result() юзать, а Uint64()

2022-04-02 15:43 UTC, TonyBlock commented on redis/redis.go
> +		return customErrors.ErrUserNotFound
Оставь подстановку конкретной ошибки другим слоям

2022-04-02 18:08 UTC, TonyBlock approved these changes

2022-04-02 18:08 UTC, shevvvo approved these changes

2022-04-02 18:16 UTC, Victorius19 approved these changes

2022-04-02 18:20 UTC, merged