PLANEXA-2: добавить начальные хэндлеры
go-park-mail-ru/2022_1_SamoeKrNaz pull request #9
Opened 2022-03-30 08:45 UTC by shevvvo

2022-03-30 13:30 UTC, TonyBlock requested changes
Выглядит вполне правдоподобно)

2022-03-30 13:30 UTC, TonyBlock commented on handlers/board_handler.go
> +func GetBoards(c *gin.Context) {
Надо бы еще добавить получение конкретной доски

2022-03-30 13:30 UTC, TonyBlock commented on handlers/handlers.go
>  import (
Я так понимаю, ты решил не удалять этот файл, да?

2022-04-01 08:39 UTC, TonyBlock requested changes

2022-04-01 08:39 UTC, TonyBlock commented on initial_router_config.go
> +		mainRoutes.DELETE(routes.BoardRoute+"/:id", middleware.CheckAuth, handlers.DeleteBoard)
Раз у тебя несколько обработчиков на BoardRoute, то может их сгруппировать по аналогии с mainRoutes?

2022-04-01 08:39 UTC, TonyBlock commented on handlers/board_handler.go
> +		c.JSON(customErrors.ConvertErrorToCode(customErrors.ErrBadInputData), gin.H{"error": customErrors.ErrBadInputData.Error()})
Просто пробрасывай ошибку, которая вернулась из юзкейса. Ты же не можешь знать наверняка, произошла ли ошибка от неправильных данных или из-за поломки бд

2022-04-01 08:39 UTC, TonyBlock commented on handlers/board_handler.go
> +	c.JSON(http.StatusCreated, gin.H{"created": true, "boardId": board.Id})
Поле created, думаю, можно не возвращать

2022-04-01 08:39 UTC, TonyBlock commented on handlers/board_handler.go
> +		c.JSON(customErrors.ConvertErrorToCode(customErrors.ErrBadInputData), gin.H{"error": customErrors.ErrBadInputData.Error()})
Просто пробрасывай ошибку, которая вернулась из юзкейса. Ты же не можешь знать наверняка, произошла ли ошибка от неправильных данных или из-за поломки бд

2022-04-01 08:39 UTC, TonyBlock commented on handlers/list_handler.go
> +	c.JSON(http.StatusOK, listId)
За это могут на рк дать по шапке. Причина: неконсистентность api. Ты во всех остальных местах возвращаешь данные в виде json, а здесь - просто число

2022-04-01 08:39 UTC, TonyBlock commented on handlers/list_handler.go
> +		c.JSON(customErrors.ConvertErrorToCode(customErrors.ErrBadInputData), gin.H{"error": customErrors.ErrBadInputData.Error()})
Просто пробрасывай ошибку, которая вернулась из юзкейса. Ты же не можешь знать наверняка, произошла ли ошибка от неправильных данных или из-за поломки бд

2022-04-01 08:39 UTC, TonyBlock commented on handlers/task_handler.go
> +		c.JSON(customErrors.ConvertErrorToCode(customErrors.ErrBadInputData), gin.H{"error": customErrors.ErrBadInputData.Error()})
Просто пробрасывай ошибку, которая вернулась из юзкейса. Ты же не можешь знать наверняка, произошла ли ошибка от неправильных данных или из-за поломки бд

2022-04-01 08:39 UTC, TonyBlock commented on handlers/task_handler.go
> +	c.JSON(http.StatusOK, taskId)
За это могут на рк дать по шапке. Причина: неконсистентность api. Ты во всех остальных местах возвращаешь данные в виде json, а здесь - просто число

2022-04-01 08:39 UTC, TonyBlock commented on usecases/user_usecase.go
> +	// получаю из бд всю инфу по айдишнику
Всю инфу не надо. Поле с паролем надо будет очистить

2022-04-01 08:40 UTC, TonyBlock requested changes

2022-04-01 08:40 UTC, TonyBlock commented on handlers/user_handler.go
> +	c.JSON(customErrors.ConvertErrorToCode(err), gin.H{"error": err.Error()})
Логичнее будет поменять местами и сделать if err != nil { // возврат ошибки }

2022-04-02 09:53 UTC, TonyBlock approved these changes

2022-04-02 16:19 UTC, Victorius19 approved these changes

2022-04-02 16:24 UTC, yalublukotikov approved these changes

2022-04-02 18:09 UTC, merged